places = ["USA", "Germany", "Russia", "India", "Newzealand"]
print(places)
sort_places = sorted(places)
print(sort_places)
sort_newplaces = sorted(places, reverse = True)
print(sort_newplaces)
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(reverse = True)
print(places)
